# taken from viluon/lession-hs
# inspired by https://github.com/docker/build-push-action/blob/a63b18d/docs/advanced/cache.md#github-cache

name: Entangled container CI
on:
  push:
    branches: [main, setup/*, update/*]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: set up Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-ent-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-ent-

    - name: login to GH container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: entangled.Dockerfile
        push: true
        tags: ghcr.io/viluon/special-entangled:latest
        build-args: |
          GHC_VERSION=8.8.4
          STACK_RESOLVER=lts-16.12
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

# TODO: Trigger release on tag, publish containers.
